### ISSUE TITLE
Port changes to Pressflow?

### ISSUE THREAD

**Issue by damienmckenna** [d6lts/drupal#24]
Are there plans to port the PHP 7.2 fixes to the Pressflow fork?

**Comment by damienmckenna** [comment]
Or even the pantheon/drops-6 repo?

**Comment by dsnopek** [comment]
I made a PR to Pressflow:

https://github.com/pressflow/6/pull/122

I can vouch for the fact that it doesn't break everything, because we're already using it with our customers.

However, I don't know that it fixes all the PHP 7 problems in Pressflow, and perhaps we'd want to do some of those changes a little different (there's code to support `decode_entities()` that'll even work for PHP 5.2, but I think Pressflow only supports PHP 5.3+ anyway).

**Comment by damienmckenna** [comment]
That's good to know.

Do any of your clients use Pantheon?

**Comment by dsnopek** [comment]
> Do any of your clients use Pantheon?

Yes. We basically just apply the patch of the Pressflow changes to them. We had our own Pantheon D6 upstream, but it turned out to be more trouble than it's worth.

**Comment by damienmckenna** [comment]
Do you use the drop-6 repo or the pressflow repo?

**Comment by dsnopek** [comment]
Sorry for not noticing this last reply!

In any case, these changes have been merged into pressflow and drops-6 at this point :-)
