### ISSUE TITLE
replace ereg_replace and other removed functions

### ISSUE THREAD

**Issue by yakovyarmo** [d6lts/drupal#58]
Hi,
If this release of drupal 6 suppose to support php 7,
How there are php functions that doesn't exits in php 7?
Like ereg_replace and others?

**Comment by dsnopek** [comment]
A shim for ereg and related functions was added:

https://github.com/d6lts/drupal/blob/6.x/includes/bootstrap.inc#L1767

This approach was chosen because contrib modules and custom code could also use ereg and in some cases was the only PHP 7 incompatible thing, avoid some porting work.

We're not going to remove the shim, but I could see an argument for changing code in core itself that uses ereg?

**Comment by yakovyarmo** [comment]
I'm sorry,
I totally missed the shim.
So now the only reason to change the code is only to make it more readable.

Thanks for all the work you guys put in to it.
