### ISSUE TITLE
Workaround for multi-byte characters

### ISSUE THREAD

**Issue by micahw156** [d6lts/drupal#67]
I know it's not possible to add multi-byte support to Drupal 6, but I have a situation where users sometimes include emoji when posting to our Drupal 6 issue tracker website, which causes node or comment creation to fail. I'd like to build in some protections against this.

I'm opening this issue in hopes of sanity checking my workaround, and looking for feedback if this is a stupid idea.

I'm thinking that i might just be able to hack **db_escape_string()** to add this line:

`$text = iconv("utf-8", "utf-8//ignore", $text);`

Is there any reason this would be a particularly horrible idea, and/or am I putting this hack in the wrong place?

**Comment by micahw156** [comment]
No, it won't work, because utf8mb4 characters are still utf-8. Hmmm.

**Comment by micahw156** [comment]
I think I found a solution in [this post](https://stackoverflow.com/questions/16496554/can-php-detect-4-byte-encoded-utf8-chars) that seems to be working and stripped the characters. Posting my workaround here in case anyone else runs into this problem.

```
diff --git a/includes/database.mysqli.inc b/includes/database.mysqli.inc
index b373730..2fee64d 100644
--- a/includes/database.mysqli.inc
+++ b/includes/database.mysqli.inc
@@ -333,6 +333,14 @@ function db_decode_blob($data) {
  */
 function db_escape_string($text) {
   global $active_db;
+
+  // @see https://stackoverflow.com/questions/16496554/can-php-detect-4-byte-encoded-utf8-chars
+  $text = preg_replace('%(?:
+      \xF0[\x90-\xBF][\x80-\xBF]{2}      # planes 1-3
+    | [\xF1-\xF3][\x80-\xBF]{3}          # planes 4-15
+    | \xF4[\x80-\x8F][\x80-\xBF]{2}      # plane 16
+  )%xs', '', $text);
+
   return mysqli_real_escape_string($active_db, $text);
 }
 
```

**Comment by Muppetteer** [comment]
I've been running D6 / Pressflow using utf8mb4 for a long time and users can post emoji in nodes and comments without issue. Character stripping is not required. These are my notes on what I did:

- Take site offline
- Backup database
- Change your database collation.
`ALTER DATABASE drupal CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;`

- Convert your tables using the SQL generated by this statement (note I have every table using innodb which you may not, no idea if it matters)
`SELECT "SET foreign_key_checks = 0;"
UNION
SELECT DISTINCT
  CONCAT("ALTER TABLE ", TABLE_NAME," CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;") AS queries
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA="drupal"
  AND TABLE_TYPE="BASE TABLE"
UNION
SELECT "SET foreign_key_checks = 1;";`

- Change a couple of Drupal files to use utf8mb4 instead of utf8:
/includes/database.mysql-common.inc (db_create_table_sql DEFAULT CHARACTER SET...)
/includes/database.mysql.inc (SET NAMES...)
/includes/database.mysqli.inc (SET NAMES...)
/sites/whatever/settings.php ($db_collation = 'utf8mb4_unicode_ci';)

- Optimise all tables in mysql
- Change the default character set and collation for the database in my.cnf. Optional

```
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

- Restart mysql and bring Drupal back online.

Obviously YMMV but this has been working for me for a couple of years now.

**Comment by micahw156** [comment]
@Muppetteer thanks so much! I will give this a try!
