### ISSUE TITLE
XSS Vulnerability - 1

### ISSUE THREAD

**Issue by golanorbi** [d6lts/drupal#70]
An XSS vulnerability has been found in Drupal Core that is related to the jQuery UI contrib module:

* CVE-2021-41183: XSS in the of option of the .position() util [4]

For more details:

https://www.drupal.org/sa-core-2022-001

The suggested solution:

Install the latest version:

   * If you are using Drupal 9.3, update to Drupal 9.3.3 [6].
   * If you are using Drupal 9.2, update to Drupal 9.2.11 [7].
   * If you are using Drupal 7, update to Drupal 7.86 [8].

All versions of Drupal 8 and 9 prior to 9.2.x are end-of-life and do not receive security coverage. Note that Drupal 8 has reached its end of life [9].

Is there a Drupal 6.60 release that fixes the these XSS vulnerabilities?

**Comment by dsnopek** [comment]
This is about a vulnerability in jQuery UI, which isn't included in Drupal 6 core. There was a security release made for the jquery_ui module:

https://github.com/d6lts/jquery_ui/releases/tag/6.x-1.6

... however, this vulnerability actually doesn't apply, because the versions of jQuery UI used by the D6 'jquery_ui' module (1.6 and 1.7) don't include the position plugin.

**Comment by golanorbi** [comment]
`It is possible that this vulnerability is exploitable with some Drupal modules. As a precaution, this Drupal security release applies the fix for the above cross-site description issue, without making any of the other changes to the jQuery version that is included in Drupal.`

It says that the fix was made in Drupal Core, and not in jQuery UI module.
jQuery UI module stayed untouched regarding this vulnerability.
So, is there a plan to issue a Drupal 6.60 to fix this?
